//! Parser für `Cargo.lock`.
//!
//! Liest ausschließlich die `[[package]]`-Tabellen; es wird kein
//! `cargo`-Subprozess gestartet. Siehe AP W1-14..17, Abschnitt `lockfile.rs`.

use std::fs;
use std::path::Path;

use serde::Deserialize;

use crate::error::CodeGraphResult;

/// Eine im Lockfile gesperrte Paketversion.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedPackage {
    /// Crate-Name.
    pub name: String,
    /// Gesperrte Version.
    pub version: String,
    /// Quelle (z. B. `registry+https://...`); `None` bei Path-Dependencies.
    pub source: Option<String>,
    /// Prüfsumme, falls im Lockfile vorhanden.
    pub checksum: Option<String>,
}

/// Rohform des gesamten Lockfiles: nur die `[[package]]`-Einträge werden
/// benötigt, alle anderen Top-Level-Felder (z. B. `version`) werden ignoriert.
#[derive(Debug, Deserialize)]
struct RawLockfile {
    #[serde(default, rename = "package")]
    packages: Vec<RawLockedPackage>,
}

#[derive(Debug, Deserialize)]
struct RawLockedPackage {
    name: String,
    version: String,
    #[serde(default)]
    source: Option<String>,
    #[serde(default)]
    checksum: Option<String>,
}

/// Parst `<root>/Cargo.lock`. Fehlt die Datei, wird `Ok(vec![])`
/// zurückgegeben statt eines Fehlers.
pub fn parse_lockfile(root: &Path) -> CodeGraphResult<Vec<LockedPackage>> {
    let lockfile_path = root.join("Cargo.lock");
    if !lockfile_path.is_file() {
        return Ok(Vec::new());
    }
    let content = fs::read_to_string(&lockfile_path)?;
    let raw: RawLockfile = toml::from_str(&content)?;
    Ok(raw
        .packages
        .into_iter()
        .map(|pkg| LockedPackage {
            name: pkg.name,
            version: pkg.version,
            source: pkg.source,
            checksum: pkg.checksum,
        })
        .collect())
}

/// Sucht das erste gesperrte Paket mit passendem Namen.
#[must_use]
pub fn find_locked<'a>(packages: &'a [LockedPackage], name: &str) -> Option<&'a LockedPackage> {
    packages.iter().find(|pkg| pkg.name == name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn scratch_dir(label: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("harw-code-graph-{}-{label}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).expect("Scratch-Verzeichnis anlegen");
        dir
    }

    #[test]
    fn parse_lockfile_reads_written_fixture() {
        let root = scratch_dir("lockfile");
        let lock_content = r#"
# This file is automatically generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"

[[package]]
name = "harw-types"
version = "0.2.0"
"#;
        fs::write(root.join("Cargo.lock"), lock_content).expect("Cargo.lock schreiben");

        let packages = parse_lockfile(&root).expect("Lockfile parsen");
        assert_eq!(packages.len(), 2);

        let serde_pkg = find_locked(&packages, "serde").expect("serde gefunden");
        assert_eq!(serde_pkg.version, "1.0.228");
        assert_eq!(serde_pkg.checksum.as_deref(), Some("abc123"));

        let harw_types_pkg = find_locked(&packages, "harw-types").expect("harw-types gefunden");
        assert_eq!(harw_types_pkg.source, None);

        assert!(find_locked(&packages, "does-not-exist").is_none());

        fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn parse_lockfile_missing_file_returns_empty_vec() {
        let root = scratch_dir("lockfile-missing");
        let packages = parse_lockfile(&root).expect("fehlendes Lockfile ergibt leeren Vec");
        assert!(packages.is_empty());
        fs::remove_dir_all(&root).ok();
    }
}
