//! Baseline system-prompt builder and `InstructionsProvider` implementation.
//!
//! See design spec: `harw-instructions` crate spec, section "baseline.rs".
//!
//! Responsibilities:
//! - [`AgentIdentity`]: holds all agent-grounding data and renders the system prompt.
//! - [`BaselineInstructionsProvider`]: adapts `AgentIdentity` to the
//!   [`harw_extension_api::InstructionsProvider`] trait so it can be registered
//!   in an [`harw_extension_api::ExtensionRegistry`]. Generated by
//!   `#[harw_macros::instructions_provider]` from the [`baseline_instructions`]
//!   function below; see that function's doc for the full behavioral contract
//!   (the struct's own rustdoc is forwarded from there by the macro).

// `InstructionsProvider` wird nicht mehr importiert: seit der Migration auf
// `#[instructions_provider]` implementiert das Makro den Trait, nicht diese
// Datei.
use harw_extension_api::LoadedInstructions;
use harw_macros::instructions_provider;

/// All data needed to ground the model in its operational context.
///
/// # Description
/// Carries the agent's name, role, working directory, project root, available
/// tools, and any extra free-form context fragments. The builder methods allow
/// incremental configuration after construction via [`AgentIdentity::new`].
///
/// # Examples
/// ```rust,no_run
/// use harw_instructions::AgentIdentity;
///
/// let identity = AgentIdentity::new("harw", "/home/user/project")
///     .with_role("coding agent")
///     .with_tools(vec!["fs.read".to_owned(), "fs.write".to_owned()]);
///
/// let prompt = identity.render_system_prompt();
/// assert!(prompt.contains("harw"));
/// ```
#[derive(Debug, Clone)]
pub struct AgentIdentity {
    /// The short name of the agent (e.g. `"harw"`).
    pub agent_name: String,
    /// Human-readable role description (e.g. `"coding agent"`).
    pub role_description: String,
    /// Absolute path of the current working directory.
    pub cwd: String,
    /// Absolute path of the project root (may equal `cwd`).
    pub project_root: String,
    /// Names of tools currently registered and available to the model.
    pub tools_available: Vec<String>,
    /// Optional free-form fragments appended to [`LoadedInstructions::fragments`].
    pub extra_context: Vec<String>,
    /// Optionaler Modus-Abschnitt, üblicherweise aus `InteractionMode::prompt_section`.
    ///
    /// `None` bedeutet: der Prompt führt keinen Modus-Abschnitt. Der Wert wird
    /// unverändert in [`AgentIdentity::render_system_prompt`] übernommen.
    pub mode_section: Option<String>,
    /// Optionaler Rückgabevertrag, den dieser Agent einhalten muss.
    ///
    /// Typischerweise das JSON-Schema eines `ResearchFinding` oder eines
    /// Planvorschlags. `None` bedeutet: freie Antwort in Prosa.
    pub return_contract: Option<String>,
    /// Ob der Systemprompt den Abschnitt zur Zwei-Block-Konvention
    /// (Knoten AW4-01, [`crate::trust_boundary::context_blocks_section`])
    /// trägt.
    ///
    /// `false` (Voreinstellung über [`AgentIdentity::new`]) bedeutet: der
    /// Prompt bleibt zeichengleich zur Fassung vor dieser Erweiterung. Nur
    /// [`AgentIdentity::with_trust_boundary_notice`] setzt ihn auf `true`.
    /// Ob ein Aufrufer das tut, hängt davon ab, ob sein Montagepfad
    /// (`harw_core::context_budget::ContextAssemblyV2::render_trust_blocks`)
    /// überhaupt Zwei-Block-Rendering verwendet — diese Datei trifft diese
    /// Entscheidung nicht selbst.
    pub trust_boundary_notice_enabled: bool,
}

impl AgentIdentity {
    /// Constructs a new `AgentIdentity` with sensible defaults.
    ///
    /// # Description
    /// `role_description` defaults to `"coding agent"`.
    /// `project_root` defaults to `cwd`.
    /// `tools_available` and `extra_context` are empty.
    /// `mode_section` and `return_contract` are `None`.
    ///
    /// # Arguments
    /// - `agent_name` (`impl Into<String>`): the agent's short identifier.
    /// - `cwd` (`impl Into<String>`): absolute path of the current working directory.
    ///
    /// # Returns
    /// A fully initialised `AgentIdentity` ready for optional builder-chaining.
    ///
    /// # Examples
    /// ```rust
    /// use harw_instructions::AgentIdentity;
    ///
    /// let id = AgentIdentity::new("harw", "/workspace");
    /// assert_eq!(id.agent_name, "harw");
    /// assert_eq!(id.project_root, "/workspace");
    /// ```
    pub fn new(agent_name: impl Into<String>, cwd: impl Into<String>) -> Self {
        let cwd_str = cwd.into();
        Self {
            agent_name: agent_name.into(),
            role_description: "coding agent".to_owned(),
            project_root: cwd_str.clone(),
            cwd: cwd_str,
            tools_available: Vec::new(),
            extra_context: Vec::new(),
            mode_section: None,
            return_contract: None,
            trust_boundary_notice_enabled: false,
        }
    }

    /// Overrides the role description.
    ///
    /// # Arguments
    /// - `role` (`impl Into<String>`): human-readable role label.
    ///
    /// # Returns
    /// `self` with `role_description` replaced.
    ///
    /// # Examples
    /// ```rust
    /// use harw_instructions::AgentIdentity;
    ///
    /// let id = AgentIdentity::new("harw", "/ws").with_role("refactoring agent");
    /// assert_eq!(id.role_description, "refactoring agent");
    /// ```
    pub fn with_role(mut self, role: impl Into<String>) -> Self {
        self.role_description = role.into();
        self
    }

    /// Sets the project root to a path that may differ from `cwd`.
    ///
    /// # Arguments
    /// - `root` (`impl Into<String>`): absolute path to the project root.
    ///
    /// # Returns
    /// `self` with `project_root` replaced.
    ///
    /// # Examples
    /// ```rust
    /// use harw_instructions::AgentIdentity;
    ///
    /// let id = AgentIdentity::new("harw", "/ws/sub").with_project_root("/ws");
    /// assert_eq!(id.project_root, "/ws");
    /// ```
    pub fn with_project_root(mut self, root: impl Into<String>) -> Self {
        self.project_root = root.into();
        self
    }

    /// Replaces the tools list.
    ///
    /// # Arguments
    /// - `tools` (`Vec<String>`): tool names that are currently registered.
    ///
    /// # Returns
    /// `self` with `tools_available` replaced.
    ///
    /// # Examples
    /// ```rust
    /// use harw_instructions::AgentIdentity;
    ///
    /// let id = AgentIdentity::new("harw", "/ws")
    ///     .with_tools(vec!["fs.read".to_owned()]);
    /// assert_eq!(id.tools_available.len(), 1);
    /// ```
    pub fn with_tools(mut self, tools: Vec<String>) -> Self {
        self.tools_available = tools;
        self
    }

    /// Appends free-form context fragments to be forwarded in [`LoadedInstructions::fragments`].
    ///
    /// # Arguments
    /// - `ctx` (`Vec<String>`): arbitrary text fragments.
    ///
    /// # Returns
    /// `self` with `extra_context` replaced.
    ///
    /// # Examples
    /// ```rust
    /// use harw_instructions::AgentIdentity;
    ///
    /// let id = AgentIdentity::new("harw", "/ws")
    ///     .with_extra_context(vec!["Use tabs for indentation.".to_owned()]);
    /// assert_eq!(id.extra_context.len(), 1);
    /// ```
    pub fn with_extra_context(mut self, ctx: Vec<String>) -> Self {
        self.extra_context = ctx;
        self
    }

    /// Ergänzt den Modus-Abschnitt (aus `InteractionMode::prompt_section`).
    ///
    /// # Beschreibung
    /// Der Abschnitt beschreibt, in welchem Interaktionsmodus der Agent
    /// arbeitet (etwa „nur planen, nichts schreiben"). Er wird von
    /// [`AgentIdentity::render_system_prompt`] unverändert unter einer eigenen
    /// Überschrift angehängt. Ein erneuter Aufruf ersetzt den vorherigen Wert.
    ///
    /// # Argumente
    /// - `section` (`impl Into<String>`): der fertig formulierte Abschnittstext.
    ///
    /// # Rückgabe
    /// `self` mit gesetztem `mode_section`.
    ///
    /// # Beispiele
    /// ```rust
    /// use harw_instructions::AgentIdentity;
    ///
    /// let id = AgentIdentity::new("harw", "/ws")
    ///     .with_mode_section("You are in read-only exploration mode.");
    /// assert!(id.render_system_prompt().contains("read-only exploration mode"));
    /// ```
    pub fn with_mode_section(mut self, section: impl Into<String>) -> Self {
        self.mode_section = Some(section.into());
        self
    }

    /// Ergänzt den Return-Contract, den dieser Agent einhalten muss
    /// (z. B. das JSON-Schema eines `ResearchFinding`).
    ///
    /// # Beschreibung
    /// [`AgentIdentity::render_system_prompt`] hängt den Vertrag unter einer
    /// eigenen Überschrift an, zusammen mit einer unmissverständlichen
    /// Anweisung: die gesamte Endantwort ist genau ein JSON-Dokument dieser
    /// Form — keine Prosa, kein Code-Fence, keine Erklärung. Diese Anweisung
    /// hat ausdrücklich Vorrang vor der Sprachregel der Grundanweisungen.
    /// Ein erneuter Aufruf ersetzt den vorherigen Wert.
    ///
    /// # Argumente
    /// - `contract` (`impl Into<String>`): das Schema oder die Vertragsbeschreibung.
    ///
    /// # Rückgabe
    /// `self` mit gesetztem `return_contract`.
    ///
    /// # Beispiele
    /// ```rust
    /// use harw_instructions::AgentIdentity;
    ///
    /// let prompt = AgentIdentity::new("harw", "/ws")
    ///     .with_return_contract(r#"{ "finding": "string", "evidence": ["string"] }"#)
    ///     .render_system_prompt();
    /// assert!(prompt.contains("## Return contract"));
    /// assert!(prompt.contains("\"evidence\""));
    /// ```
    pub fn with_return_contract(mut self, contract: impl Into<String>) -> Self {
        self.return_contract = Some(contract.into());
        self
    }

    /// Aktiviert den Systemprompt-Abschnitt zur Zwei-Block-Konvention
    /// (Knoten AW4-01).
    ///
    /// # Description
    /// Setzt [`AgentIdentity::trust_boundary_notice_enabled`] auf `true`.
    /// [`AgentIdentity::render_system_prompt`] hängt danach `## Context
    /// blocks` mit [`crate::trust_boundary::context_blocks_section`] an —
    /// vor `## Interaction mode` und `## Return contract`, weil die
    /// Blockkonvention Grundlagenwissen ist (wie `## Behavioral rules`),
    /// kein Verhalten für diesen einen Turn. Ohne diesen Aufruf bleibt der
    /// Prompt zeichengleich zur Fassung vor dieser Erweiterung.
    ///
    /// # Returns
    /// `self` mit aktiviertem Abschnitt.
    ///
    /// # Examples
    /// ```rust
    /// use harw_instructions::AgentIdentity;
    ///
    /// let prompt = AgentIdentity::new("harw", "/ws")
    ///     .with_trust_boundary_notice()
    ///     .render_system_prompt();
    /// assert!(prompt.contains("## Context blocks"));
    /// ```
    #[must_use]
    pub fn with_trust_boundary_notice(mut self) -> Self {
        self.trust_boundary_notice_enabled = true;
        self
    }

    /// Renders the complete system-prompt string from the stored identity data.
    ///
    /// # Description
    /// Produces a structured prompt that grounds the model in its operating
    /// environment: agent name, role, cwd, project root, OS, tool inventory,
    /// and behavioral rules. When `tools_available` is empty the tools section
    /// emits `"No tools are currently registered."` instead of a numbered list.
    ///
    /// Ist [`AgentIdentity::trust_boundary_notice_enabled`] gesetzt (über
    /// [`AgentIdentity::with_trust_boundary_notice`]), folgt als Nächstes
    /// `## Context blocks` mit [`crate::trust_boundary::context_blocks_section`]
    /// — die Erklärung der Zwei-Block-Konvention (Knoten AW4-01), **vor**
    /// den beiden folgenden Abschnitten, weil sie Grundlagenwissen ist.
    ///
    /// Sind [`AgentIdentity::mode_section`] bzw.
    /// [`AgentIdentity::return_contract`] gesetzt, folgen darauf zwei weitere
    /// Abschnitte: `## Interaction mode` mit dem Modus-Text und
    /// `## Return contract` mit der Anweisung, ausschließlich ein JSON-Dokument
    /// der angegebenen Form zurückzugeben. Ist keines der drei gesetzt, ist
    /// die Ausgabe zeichengleich mit der Ausgabe vor dieser Erweiterung.
    ///
    /// # Returns
    /// A `String` ready to be used as the `system_prompt` field of
    /// [`LoadedInstructions`].
    ///
    /// # Examples
    /// ```rust
    /// use harw_instructions::AgentIdentity;
    ///
    /// let prompt = AgentIdentity::new("harw", "/workspace")
    ///     .with_tools(vec!["fs.read".to_owned()])
    ///     .render_system_prompt();
    ///
    /// assert!(prompt.contains("harw"));
    /// assert!(prompt.contains("/workspace"));
    /// assert!(prompt.contains("1. fs.read"));
    /// ```
    pub fn render_system_prompt(&self) -> String {
        let os_name = std::env::consts::OS;

        let tools_section = if self.tools_available.is_empty() {
            "No tools are currently registered.".to_owned()
        } else {
            self.tools_available
                .iter()
                .enumerate()
                .map(|(i, t)| format!("{}. {}", i + 1, t))
                .collect::<Vec<_>>()
                .join("\n")
        };

        let mut prompt = format!(
            "You are {agent_name}, a {role_description} operating inside a local Rust workspace.\n\
\n\
## Working environment\n\
- Current working directory: `{cwd}`\n\
- Project root: `{project_root}`\n\
- Operating system: {os_name}\n\
\n\
## Available tools\n\
{tools_section}\n\
\n\
## Behavioral rules\n\
- You DO have access to the local filesystem via the tools above. Do not tell the user you are just a language model without file access.\n\
- Always resolve file paths relative to the project root shown above.\n\
- Prefer targeted reads (fs.read on specific files) over broad shell commands.\n\
- Before writing, verify the target path exists in the intended scope.\n\
- When a request is ambiguous, ask ONE targeted clarifying question — do not enumerate all possible interpretations.\n\
- Respond in the user's language.",
            agent_name = self.agent_name,
            role_description = self.role_description,
            cwd = self.cwd,
            project_root = self.project_root,
            os_name = os_name,
            tools_section = tools_section,
        );

        // Optionale Abschnitte. Ohne sie bleibt der Prompt zeichengleich zur
        // Fassung vor dieser Erweiterung — bestehende Aufrufer sehen keine
        // Änderung.
        //
        // Reihenfolge: `## Context blocks` zuerst, weil es Grundlagenwissen
        // ist (wie `## Behavioral rules` oben) — keine Anweisung für diesen
        // einen Turn wie `## Interaction mode`, und kein Vertrag, der laut
        // seinem eigenen Text Vorrang vor allem anderen beansprucht wie
        // `## Return contract` (das deshalb zuletzt bleibt).
        if self.trust_boundary_notice_enabled {
            prompt.push_str("\n\n## Context blocks\n");
            prompt.push_str(&crate::trust_boundary::context_blocks_section());
        }

        if let Some(mode_section) = &self.mode_section {
            prompt.push_str("\n\n## Interaction mode\n");
            prompt.push_str(mode_section);
        }

        if let Some(return_contract) = &self.return_contract {
            prompt.push_str(
                "\n\n## Return contract\n\
Your entire final message MUST be exactly one JSON document matching the contract below — and nothing else. \
No prose before or after it, no markdown code fence, no explanation, no apology. \
This rule overrides every other instruction above, including the language rule: the contract wins.\n\n",
            );
            prompt.push_str(return_contract);
        }

        prompt
    }
}

/// Adapts [`AgentIdentity`] to the [`InstructionsProvider`] trait.
///
/// # Description
/// Wraps the [`AgentIdentity`] captured as `state` and implements
/// `InstructionsProvider::load` by calling
/// [`AgentIdentity::render_system_prompt`] and returning the result together
/// with any extra context fragments. Register this in an `ExtensionRegistry`
/// to ensure the model receives baseline grounding on every session start.
///
/// # Arguments
///
/// - `state` (`&AgentIdentity`): the agent grounding data to render.
///
/// # Returns
///
/// A [`LoadedInstructions`] whose `system_prompt` is
/// [`AgentIdentity::render_system_prompt`]'s output and whose `fragments` is
/// `state.extra_context.clone()`.
///
/// # Concurrency
/// `Send + Sync` — the inner `AgentIdentity` contains only owned `String`/`Vec`
/// values and is read by reference inside the returned future's closure.
///
/// # Examples
/// ```rust,no_run
/// use harw_instructions::{AgentIdentity, BaselineInstructionsProvider};
/// use harw_extension_api::InstructionsProvider;
///
/// let provider = BaselineInstructionsProvider::new(
///     AgentIdentity::new("harw", "/workspace"),
/// );
/// ```
#[instructions_provider]
async fn baseline_instructions(state: &AgentIdentity) -> LoadedInstructions {
    LoadedInstructions {
        system_prompt: state.render_system_prompt(),
        fragments: state.extra_context.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use harw_extension_api::InstructionsProvider;

    #[test]
    fn test_identity_new_defaults() {
        let id = AgentIdentity::new("harw", "/workspace");
        assert_eq!(id.agent_name, "harw");
        assert_eq!(id.cwd, "/workspace");
        assert_eq!(id.project_root, "/workspace");
        assert_eq!(id.role_description, "coding agent");
        assert!(id.tools_available.is_empty());
        assert!(id.extra_context.is_empty());
    }

    #[test]
    fn test_identity_with_role_and_tools_builder_chain() {
        let id = AgentIdentity::new("harw", "/ws")
            .with_role("refactoring agent")
            .with_project_root("/srv/project")
            .with_tools(vec!["fs.read".to_owned(), "fs.write".to_owned()])
            .with_extra_context(vec!["Use spaces.".to_owned()]);

        assert_eq!(id.role_description, "refactoring agent");
        assert_eq!(id.project_root, "/srv/project");
        assert_eq!(id.tools_available, vec!["fs.read", "fs.write"]);
        assert_eq!(id.extra_context, vec!["Use spaces."]);
    }

    #[test]
    fn test_render_includes_cwd_and_project_root() {
        let prompt = AgentIdentity::new("harw", "/the/cwd")
            .with_project_root("/the/root")
            .render_system_prompt();

        assert!(prompt.contains("`/the/cwd`"), "prompt must contain the cwd");
        assert!(
            prompt.contains("`/the/root`"),
            "prompt must contain the project root"
        );
        assert!(prompt.contains("harw"), "prompt must contain agent name");
        assert!(
            prompt.contains("coding agent"),
            "prompt must contain role description"
        );
        assert!(
            prompt.contains(std::env::consts::OS),
            "prompt must contain OS name"
        );
    }

    #[test]
    fn test_render_lists_tools_or_none_marker() {
        // With tools — should produce a numbered list.
        let prompt_with = AgentIdentity::new("harw", "/ws")
            .with_tools(vec!["fs.read".to_owned(), "shell.exec".to_owned()])
            .render_system_prompt();

        assert!(prompt_with.contains("1. fs.read"));
        assert!(prompt_with.contains("2. shell.exec"));
        assert!(!prompt_with.contains("No tools are currently registered."));

        // Without tools — should produce the fallback marker.
        let prompt_empty = AgentIdentity::new("harw", "/ws").render_system_prompt();
        assert!(prompt_empty.contains("No tools are currently registered."));
    }

    #[test]
    fn test_identity_new_leaves_mode_section_and_return_contract_unset() {
        let id = AgentIdentity::new("harw", "/ws");
        assert!(id.mode_section.is_none());
        assert!(id.return_contract.is_none());
    }

    #[test]
    fn test_render_omits_optional_sections_when_unset() {
        let prompt = AgentIdentity::new("harw", "/ws")
            .with_tools(vec!["fs.read".to_owned()])
            .render_system_prompt();

        assert!(!prompt.contains("## Interaction mode"));
        assert!(!prompt.contains("## Return contract"));
        // Der Prompt endet unverändert mit der letzten Verhaltensregel.
        assert!(prompt.ends_with("- Respond in the user's language."));
    }

    #[test]
    fn test_render_appends_mode_section_when_set() {
        let prompt = AgentIdentity::new("harw", "/ws")
            .with_mode_section("You are in read-only exploration mode. Do not propose edits.")
            .render_system_prompt();

        assert!(prompt.contains("## Interaction mode"));
        assert!(prompt.contains("read-only exploration mode"));
        assert!(!prompt.contains("## Return contract"));
    }

    #[test]
    fn test_render_appends_unambiguous_return_contract_section() {
        let contract = r#"{ "outcome": "string", "evidence": ["string"] }"#;
        let prompt = AgentIdentity::new("harw", "/ws")
            .with_return_contract(contract)
            .render_system_prompt();

        assert!(prompt.contains("## Return contract"));
        assert!(
            prompt.contains("exactly one JSON document"),
            "der Vertrag muss unmissverständlich formuliert sein"
        );
        assert!(
            prompt.contains("overrides every other instruction"),
            "der Vertrag muss Vorrang vor der Sprachregel beanspruchen"
        );
        assert!(prompt.ends_with(contract), "das Schema steht am Ende");
    }

    #[test]
    fn test_render_appends_mode_section_before_return_contract() {
        let prompt = AgentIdentity::new("harw", "/ws")
            .with_mode_section("Explore only.")
            .with_return_contract("{ \"finding\": \"string\" }")
            .render_system_prompt();

        let mode_at = prompt.find("## Interaction mode").expect("mode section");
        let contract_at = prompt.find("## Return contract").expect("contract section");
        assert!(
            mode_at < contract_at,
            "der Modus steht vor dem Rückgabevertrag"
        );
    }

    #[test]
    fn test_builder_methods_replace_previous_optional_values() {
        let id = AgentIdentity::new("harw", "/ws")
            .with_mode_section("first")
            .with_mode_section("second")
            .with_return_contract("contract-a")
            .with_return_contract("contract-b");

        assert_eq!(id.mode_section.as_deref(), Some("second"));
        assert_eq!(id.return_contract.as_deref(), Some("contract-b"));
    }

    #[test]
    fn test_identity_new_leaves_trust_boundary_notice_disabled() {
        let id = AgentIdentity::new("harw", "/ws");
        assert!(!id.trust_boundary_notice_enabled);
    }

    #[test]
    fn test_render_omits_context_blocks_section_when_disabled() {
        let prompt = AgentIdentity::new("harw", "/ws").render_system_prompt();
        assert!(!prompt.contains("## Context blocks"));
        // Zeichengleich zur Fassung vor dieser Erweiterung.
        assert!(prompt.ends_with("- Respond in the user's language."));
    }

    #[test]
    fn test_render_appends_context_blocks_section_when_enabled() {
        let prompt = AgentIdentity::new("harw", "/ws")
            .with_trust_boundary_notice()
            .render_system_prompt();

        assert!(prompt.contains("## Context blocks"));
        assert!(prompt.contains(crate::trust_boundary::DATA_BLOCK_NOTICE));
    }

    #[test]
    fn test_context_blocks_section_precedes_mode_and_return_contract() {
        let prompt = AgentIdentity::new("harw", "/ws")
            .with_trust_boundary_notice()
            .with_mode_section("Explore only.")
            .with_return_contract("{ \"finding\": \"string\" }")
            .render_system_prompt();

        let blocks_at = prompt.find("## Context blocks").expect("context blocks section");
        let mode_at = prompt.find("## Interaction mode").expect("mode section");
        let contract_at = prompt.find("## Return contract").expect("contract section");

        assert!(blocks_at < mode_at, "context blocks precede interaction mode");
        assert!(mode_at < contract_at, "interaction mode precedes the return contract");
    }

    #[tokio::test]
    async fn test_provider_load_returns_system_prompt_and_fragments() {
        let identity = AgentIdentity::new("harw", "/workspace")
            .with_role("coding agent")
            .with_tools(vec!["fs.read".to_owned()])
            .with_extra_context(vec!["Extra note 1.".to_owned(), "Extra note 2.".to_owned()]);

        let provider = BaselineInstructionsProvider::new(identity);
        let loaded = provider.load().await;

        assert!(
            loaded.system_prompt.contains("harw"),
            "system_prompt must mention agent name"
        );
        assert!(
            loaded.system_prompt.contains("1. fs.read"),
            "system_prompt must list the tool"
        );
        assert_eq!(
            loaded.fragments,
            vec!["Extra note 1.", "Extra note 2."],
            "fragments must match extra_context"
        );
    }

    #[tokio::test]
    async fn test_provider_load_empty_fragments_when_no_extra_context() {
        let provider = BaselineInstructionsProvider::new(AgentIdentity::new("harw", "/workspace"));
        let loaded = provider.load().await;

        assert!(
            loaded.fragments.is_empty(),
            "fragments must be empty when no extra_context set"
        );
        assert!(
            !loaded.system_prompt.is_empty(),
            "system_prompt must still be non-empty"
        );
    }

    /// Belegt explizit, dass die Migration auf `#[instructions_provider]` das
    /// Verhalten nicht verändert hat: dieselbe `AgentIdentity` liefert exakt
    /// denselben `system_prompt` wie `render_system_prompt()` direkt, sowie
    /// die unveränderten `extra_context`-Fragmente.
    #[tokio::test]
    async fn test_provider_output_matches_pre_migration_shape() {
        let identity = AgentIdentity::new("harw", "/ws")
            .with_role("refactoring agent")
            .with_extra_context(vec!["note".to_owned()]);
        let expected_prompt = identity.clone().render_system_prompt();

        let provider = BaselineInstructionsProvider::new(identity);
        let loaded = provider.load().await;

        assert_eq!(loaded.system_prompt, expected_prompt);
        assert_eq!(loaded.fragments, vec!["note".to_owned()]);
    }
}
