//! Test-Helfer für tempfile-Workspaces. Nur `#[cfg(test)]` kompiliert.
//!
//! Gemeinsam genutzt von `inventory.rs`- und `sensor.rs`-Tests, damit beide
//! dieselben Werkzeuge zum Aufbau eines Miniatur-Cargo-Workspace verwenden
//! (Vorbild: `harw-code-graph/src/workspace.rs`-Testmodul).
//!
//! Enthält außerdem den Test-Fehlertyp dieses Crates: ersetzt `panic!`/
//! `unwrap`/`expect` in Tests (Rust Coding Bible R087/R165/R182). Die
//! Helfer geben [`TestResult`] zurück und melden Fehlschläge als `Err`
//! statt zu paniken.

use std::fs;
use std::path::Path;

harw_test_support::define_test_error!(pub(crate));

/// Schreibt die Wurzel-`Cargo.toml` eines virtuellen Workspace.
pub(crate) fn write_root(root: &Path, members: &[&str]) -> TestResult {
    let members_toml = members
        .iter()
        .map(|member| format!("\"{member}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let manifest = format!("[workspace]\nmembers = [{members_toml}]\n");
    fs::write(root.join("Cargo.toml"), manifest).map_err(ctx("Wurzel-Cargo.toml schreiben"))?;
    Ok(())
}

/// Schreibt das Manifest eines Members mit internen (`path`-)Abhängigkeiten
/// und/oder externen (Registry-)Abhängigkeiten.
pub(crate) fn write_member(
    root: &Path,
    name: &str,
    internal_deps: &[&str],
    external_deps: &[&str],
) -> TestResult {
    let dir = root.join(name);
    fs::create_dir_all(&dir).map_err(ctx("Member-Verzeichnis anlegen"))?;

    let mut deps_section = String::new();
    for dep in internal_deps {
        deps_section.push_str(&format!("{dep} = {{ path = \"../{dep}\" }}\n"));
    }
    for dep in external_deps {
        deps_section.push_str(&format!("{dep} = \"1\"\n"));
    }

    let manifest = format!(
        "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\n\n[dependencies]\n{deps_section}"
    );
    fs::write(dir.join("Cargo.toml"), manifest).map_err(ctx("Member-Cargo.toml schreiben"))?;
    Ok(())
}

/// Schreibt ein `Cargo.lock` mit den angegebenen Paketen. `is_external`
/// steuert, ob ein `source`-Feld (Registry) geschrieben wird — Path-
/// Abhängigkeiten (Workspace-Member) haben in einem echten `Cargo.lock` kein
/// `source`-Feld.
pub(crate) fn write_lockfile(root: &Path, packages: &[(&str, &str, bool)]) -> TestResult {
    let mut content =
        String::from("# This file is automatically generated by Cargo.\nversion = 4\n");
    for (name, version, is_external) in packages {
        content.push_str("\n[[package]]\n");
        content.push_str(&format!("name = \"{name}\"\n"));
        content.push_str(&format!("version = \"{version}\"\n"));
        if *is_external {
            content
                .push_str("source = \"registry+https://github.com/rust-lang/crates.io-index\"\n");
        }
    }
    fs::write(root.join("Cargo.lock"), content).map_err(ctx("Cargo.lock schreiben"))?;
    Ok(())
}

/// Wie [`write_lockfile`], aber mit expliziter Kontrolle über `source` und
/// `checksum` je Eintrag, und ohne Eindeutigkeitsannahme über `name` —
/// mehrere Einträge mit demselben Namen und unterschiedlicher Version
/// erzeugen absichtlich mehrere `[[package]]`-Blöcke (F-096, F-097: reale
/// `Cargo.lock`-Dateien können dieselbe Abhängigkeit mehrfach mit
/// unterschiedlichen Versionen sperren).
pub(crate) fn write_lockfile_with_metadata(
    root: &Path,
    packages: &[(&str, &str, Option<&str>, Option<&str>)],
) -> TestResult {
    let mut content =
        String::from("# This file is automatically generated by Cargo.\nversion = 4\n");
    for (name, version, source, checksum) in packages {
        content.push_str("\n[[package]]\n");
        content.push_str(&format!("name = \"{name}\"\n"));
        content.push_str(&format!("version = \"{version}\"\n"));
        if let Some(source) = source {
            content.push_str(&format!("source = \"{source}\"\n"));
        }
        if let Some(checksum) = checksum {
            content.push_str(&format!("checksum = \"{checksum}\"\n"));
        }
    }
    fs::write(root.join("Cargo.lock"), content)
        .map_err(ctx("Cargo.lock (mit Metadaten) schreiben"))?;
    Ok(())
}
