//! Test-Helfer für tempfile-Workspaces. Nur `#[cfg(test)]` kompiliert.
//!
//! Gemeinsam genutzt von `inventory.rs`- und `sensor.rs`-Tests, damit beide
//! dieselben Werkzeuge zum Aufbau eines Miniatur-Cargo-Workspace verwenden
//! (Vorbild: `harw-code-graph/src/workspace.rs`-Testmodul).

use std::fs;
use std::path::Path;

/// Schreibt die Wurzel-`Cargo.toml` eines virtuellen Workspace.
pub(crate) fn write_root(root: &Path, members: &[&str]) {
    let members_toml = members
        .iter()
        .map(|member| format!("\"{member}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let manifest = format!("[workspace]\nmembers = [{members_toml}]\n");
    fs::write(root.join("Cargo.toml"), manifest).expect("Wurzel-Cargo.toml schreiben");
}

/// Schreibt das Manifest eines Members mit internen (`path`-)Abhängigkeiten
/// und/oder externen (Registry-)Abhängigkeiten.
pub(crate) fn write_member(root: &Path, name: &str, internal_deps: &[&str], external_deps: &[&str]) {
    let dir = root.join(name);
    fs::create_dir_all(&dir).expect("Member-Verzeichnis anlegen");

    let mut deps_section = String::new();
    for dep in internal_deps {
        deps_section.push_str(&format!("{dep} = {{ path = \"../{dep}\" }}\n"));
    }
    for dep in external_deps {
        deps_section.push_str(&format!("{dep} = \"1\"\n"));
    }

    let manifest = format!(
        "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\n\n[dependencies]\n{deps_section}"
    );
    fs::write(dir.join("Cargo.toml"), manifest).expect("Member-Cargo.toml schreiben");
}

/// Schreibt ein `Cargo.lock` mit den angegebenen Paketen. `is_external`
/// steuert, ob ein `source`-Feld (Registry) geschrieben wird — Path-
/// Abhängigkeiten (Workspace-Member) haben in einem echten `Cargo.lock` kein
/// `source`-Feld.
pub(crate) fn write_lockfile(root: &Path, packages: &[(&str, &str, bool)]) {
    let mut content =
        String::from("# This file is automatically generated by Cargo.\nversion = 4\n");
    for (name, version, is_external) in packages {
        content.push_str("\n[[package]]\n");
        content.push_str(&format!("name = \"{name}\"\n"));
        content.push_str(&format!("version = \"{version}\"\n"));
        if *is_external {
            content.push_str(
                "source = \"registry+https://github.com/rust-lang/crates.io-index\"\n",
            );
        }
    }
    fs::write(root.join("Cargo.lock"), content).expect("Cargo.lock schreiben");
}
