//! Async `ContextProvider` implementation for project discovery.
//!
//! # Responsibility
//!
//! This module wraps a [`crate::discovery::ProjectContext`] and implements the
//! [`harw_extension_api::ContextProvider`] trait, emitting a sequence of
//! [`harw_extension_api::ContextFragment`]s:
//!
//! - One `"project.root"` fragment containing the project-root and cwd paths.
//! - One `"project.doc:<filename>"` fragment per discovered doc, in root→cwd
//!   order.
//!
//! # Key Types
//!
//! - [`ProjectContextProvider`] — the provider struct (implements
//!   `ContextProvider`). Generated by `#[harw_macros::context_provider]` from
//!   the [`project_context`] function below; see that function's doc for the
//!   full behavioral contract (the struct's own rustdoc is forwarded from
//!   there by the macro).
//!
//! # Concurrency
//!
//! `ProjectContextProvider` is `Send + Sync` and may be registered with any
//! async harw runtime.

// `ContextProvider` wird nicht mehr importiert: seit der Migration auf
// `#[context_provider]` implementiert das Makro den Trait, nicht diese Datei.
use harw_extension_api::{ContextFragment, TurnInputContext};
use harw_macros::context_provider;

use crate::discovery::ProjectContext;

/// Async `ContextProvider` that emits project-root metadata and doc-cascade
/// fragments for a single `ProjectContext`.
///
/// # Description
///
/// Wraps the [`ProjectContext`] captured as `state` at construction time
/// (via the generated `ProjectContextProvider::new`). On each call to
/// [`contribute`](harw_extension_api::ContextProvider::contribute) it builds
/// and returns a `Vec` of [`ContextFragment`]s:
///
/// 1. A `"project.root"` fragment with `project_root=<path>\ncwd=<path>`.
/// 2. One `"project.doc:<filename>"` fragment per
///    [`crate::discovery::DiscoveredDoc`] in root→cwd order.
///
/// Fragments are built synchronously inside an `async` block, so the future
/// resolves immediately without any I/O.
///
/// # Arguments
///
/// - `_ctx` (`&TurnInputContext`): unused; present to satisfy the
///   `ContextProvider::contribute` signature.
/// - `state` (`&ProjectContext`): the discovery result to expose as context
///   fragments.
///
/// # Returns
///
/// A `Vec<ContextFragment>` with at least one element (the root fragment).
///
/// # Concurrency
///
/// `Send + Sync`. The inner `ProjectContext` is read-only after construction.
///
/// # Examples
///
/// ```rust,no_run
/// use harw_project_discovery::{discover_project, DiscoveryConfig, ProjectContextProvider};
/// use harw_extension_api::{ContextProvider, TurnInputContext};
/// use std::path::Path;
///
/// let cfg = DiscoveryConfig::default();
/// let ctx = discover_project(Path::new("."), &cfg).expect("discovery failed");
/// let provider = ProjectContextProvider::new(ctx);
/// // In an async context:
/// // let fragments = provider.contribute(&TurnInputContext::default()).await;
/// // assert_eq!(fragments[0].label, "project.root");
/// ```
#[context_provider]
async fn project_context(_ctx: &TurnInputContext, state: &ProjectContext) -> Vec<ContextFragment> {
    let mut out = Vec::with_capacity(1 + state.docs.len());

    // Meta-fragment: project root + cwd
    out.push(ContextFragment {
        label: "project.root".to_string(),
        content: format!(
            "project_root={}\ncwd={}",
            state.project_root.display(),
            state.cwd.display()
        ),
    });

    // One fragment per discovered doc
    for doc in &state.docs {
        out.push(ContextFragment {
            label: format!("project.doc:{}", doc.filename),
            content: doc.content.clone(),
        });
    }

    out
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::discovery::{DiscoveredDoc, ProjectContext};
    // Der Trait wird nur hier gebraucht: der Produktivcode implementiert ihn
    // seit der Migration nicht mehr selbst (das tut `#[context_provider]`),
    // aber die Tests rufen `.contribute()` darüber auf.
    use harw_extension_api::ContextProvider;
    use std::path::PathBuf;

    fn make_context(docs: Vec<DiscoveredDoc>) -> ProjectContext {
        ProjectContext {
            cwd: PathBuf::from("/work/sub"),
            project_root: PathBuf::from("/work"),
            docs,
        }
    }

    fn make_doc(filename: &str, content: &str) -> DiscoveredDoc {
        DiscoveredDoc {
            path: PathBuf::from(format!("/work/{filename}")),
            filename: filename.to_owned(),
            content: content.to_owned(),
        }
    }

    #[tokio::test]
    async fn test_provider_emits_root_fragment() {
        let provider = ProjectContextProvider::new(make_context(vec![]));
        let fragments = provider.contribute(&TurnInputContext::default()).await;

        assert!(!fragments.is_empty());
        let root = &fragments[0];
        assert_eq!(root.label, "project.root");
        assert!(root.content.contains("project_root=/work"));
        assert!(root.content.contains("cwd=/work/sub"));
    }

    #[tokio::test]
    async fn test_provider_emits_one_fragment_per_doc() {
        let docs = vec![
            make_doc("HARW.md", "root doc"),
            make_doc("HARW.md", "sub doc"),
        ];
        let provider = ProjectContextProvider::new(make_context(docs));
        let fragments = provider.contribute(&TurnInputContext::default()).await;

        // root fragment + 2 docs
        assert_eq!(fragments.len(), 3);
        assert_eq!(fragments[1].label, "project.doc:HARW.md");
        assert_eq!(fragments[1].content, "root doc");
        assert_eq!(fragments[2].label, "project.doc:HARW.md");
        assert_eq!(fragments[2].content, "sub doc");
    }

    #[tokio::test]
    async fn test_provider_empty_docs_still_emits_root_fragment() {
        let provider = ProjectContextProvider::new(make_context(vec![]));
        let fragments = provider.contribute(&TurnInputContext::default()).await;

        assert_eq!(fragments.len(), 1);
        assert_eq!(fragments[0].label, "project.root");
    }

    /// Belegt explizit, dass die Migration auf `#[context_provider]` das
    /// Verhalten nicht verändert hat: dieselbe Eingabe liefert exakt dieselben
    /// Fragmente (Reihenfolge, Label, Inhalt) wie vor der Migration.
    #[tokio::test]
    async fn test_provider_output_matches_pre_migration_shape() {
        let docs = vec![make_doc("HARW.md", "content-a")];
        let provider = ProjectContextProvider::new(make_context(docs));
        let fragments = provider.contribute(&TurnInputContext::default()).await;

        assert_eq!(
            fragments.len(),
            2,
            "root fragment + exactly one doc fragment"
        );
        assert_eq!(fragments[0].label, "project.root");
        assert_eq!(
            fragments[0].content, "project_root=/work\ncwd=/work/sub",
            "root fragment content format must be unchanged"
        );
        assert_eq!(fragments[1].label, "project.doc:HARW.md");
        assert_eq!(fragments[1].content, "content-a");
    }
}
