//! `HarwSecureFrameV1` header (Masterplan v2 §8) with a strict parser.
//!
//! # Wire layout (version 1, all integers big-endian)
//! ```text
//! magic            4 bytes   "HWSF"
//! version          u16       1
//! profile          u16       HarwCryptoProfile::id of the sender key
//! purpose          u8        HarwKeyPurpose::code of the sender key
//! key_version      u32       non-zero
//! key_id_len       u8        1..=64
//! key_id           bytes     NodeId grammar
//! sender_len       u8        1..=64
//! sender           bytes     NodeId grammar
//! sequence         u64       per-sender, for the replay window
//! issued_at_ms     u64       Unix milliseconds
//! idempotency_key  16 bytes
//! payload_len      u32       <= MAX_PAYLOAD_LEN
//! ```
//! A complete frame is `header || payload` with exactly `payload_len`
//! payload bytes. The canonical header bytes are the AEAD associated data of
//! the encrypted payload and the `header` field of the
//! [`SignTranscript::secure_frame`](crate::SignTranscript::secure_frame)
//! transcript, so every header field is authenticated twice.
//!
//! # Parser strictness
//! One encoding per header: unknown version, profile or purpose, a zero key
//! version, an invalid name, a profile that does not fit the purpose, an
//! oversize payload length and any trailing byte are all rejections. The
//! version is checked right after the magic: a future version may change
//! everything behind it.
//!
//! # Processing order (§9)
//! Parsing is step 2 ("frame version / maximum sizes"). The replay window
//! ([`crate::ReplayWindow`]) is consulted only after the sender signature
//! verified (step 10), so an unauthenticated frame never consumes replay
//! state.

use core::fmt;

use crate::error::EncryptError;
use crate::names::{HarwKeyRef, HarwKeyVersion, NodeId};
use crate::profile::HarwCryptoProfile;
use crate::purpose::HarwKeyPurpose;
use crate::transcript::Cursor;

/// Frame magic.
pub const FRAME_MAGIC: [u8; 4] = *b"HWSF";
/// The only supported frame version.
pub const FRAME_VERSION: u16 = 1;
/// Maximum payload (ciphertext) length of one frame: 1 MiB.
pub const MAX_PAYLOAD_LEN: u32 = 1 << 20;
/// Length of an [`IdempotencyKey`].
pub const IDEMPOTENCY_KEY_LEN: usize = 16;

/// Unix time in milliseconds.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct UnixMillis(pub u64);

/// Idempotency key of a mutation (§9).
///
/// # Description
/// Distinct from any crypto nonce: the nonce protects one encryption, the
/// idempotency key identifies one *intended mutation* across retries. A
/// client that timed out after `key.rotate` retries with the same key, and
/// the ledger answers with the recorded outcome instead of rotating twice.
/// Not secret; `Clone` and printable (lower-case hex).
#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct IdempotencyKey([u8; IDEMPOTENCY_KEY_LEN]);

impl IdempotencyKey {
    /// Wrap 16 bytes (generated by the caller from a CSPRNG).
    #[must_use]
    pub const fn from_bytes(bytes: [u8; IDEMPOTENCY_KEY_LEN]) -> Self {
        Self(bytes)
    }

    /// The raw bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; IDEMPOTENCY_KEY_LEN] {
        &self.0
    }
}

impl fmt::Display for IdempotencyKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for byte in self.0 {
            write!(f, "{byte:02x}")?;
        }
        Ok(())
    }
}

impl fmt::Debug for IdempotencyKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "IdempotencyKey({self})")
    }
}

/// The header of a `HarwSecureFrameV1`.
///
/// # Description
/// Fields are public; [`Self::encode`] enforces the cross-field rules
/// (profile fits purpose, payload length bound), so an inconsistent header
/// can be built but never serialized.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SecureFrameHeader {
    /// Algorithm suite of the sender key.
    pub profile: HarwCryptoProfile,
    /// Purpose of the sender key.
    pub purpose: HarwKeyPurpose,
    /// Key id (owner name) of the sender key.
    pub key_id: NodeId,
    /// Version of the sender key.
    pub key_version: HarwKeyVersion,
    /// Sending node; keys the replay window.
    pub sender: NodeId,
    /// Per-sender sequence number.
    pub sequence: u64,
    /// Issue time.
    pub issued_at: UnixMillis,
    /// Idempotency key of the carried request.
    pub idempotency_key: IdempotencyKey,
    /// Exact payload length that follows the header.
    pub payload_len: u32,
}

impl SecureFrameHeader {
    /// The sender key as a purpose-typed reference.
    #[must_use]
    pub fn key_ref(&self) -> HarwKeyRef {
        HarwKeyRef::versioned(self.purpose, self.key_id.clone(), self.key_version)
    }

    /// Check the cross-field rules.
    ///
    /// # Errors
    /// [`EncryptError::ProfileMismatch`] or
    /// [`EncryptError::FramePayloadTooLarge`].
    pub fn validate(&self) -> Result<(), EncryptError> {
        if !self.profile.supports(self.purpose) {
            return Err(EncryptError::ProfileMismatch);
        }
        if self.payload_len > MAX_PAYLOAD_LEN {
            return Err(EncryptError::FramePayloadTooLarge);
        }
        Ok(())
    }

    /// Canonical header bytes (also the AEAD associated data).
    ///
    /// # Errors
    /// See [`Self::validate`]. Name lengths cannot fail: [`NodeId`] is at
    /// most 64 bytes.
    pub fn encode(&self) -> Result<Vec<u8>, EncryptError> {
        self.validate()?;
        let key_id = self.key_id.as_str().as_bytes();
        let sender = self.sender.as_str().as_bytes();
        let key_id_len = u8::try_from(key_id.len()).map_err(|_| EncryptError::InvalidName)?;
        let sender_len = u8::try_from(sender.len()).map_err(|_| EncryptError::InvalidName)?;

        let mut out = Vec::with_capacity(
            FRAME_MAGIC.len()
                + 2
                + 2
                + 1
                + 4
                + 1
                + key_id.len()
                + 1
                + sender.len()
                + 8
                + 8
                + IDEMPOTENCY_KEY_LEN
                + 4,
        );
        out.extend_from_slice(&FRAME_MAGIC);
        out.extend_from_slice(&FRAME_VERSION.to_be_bytes());
        out.extend_from_slice(&self.profile.id().to_be_bytes());
        out.push(self.purpose.code());
        out.extend_from_slice(&self.key_version.get().to_be_bytes());
        out.push(key_id_len);
        out.extend_from_slice(key_id);
        out.push(sender_len);
        out.extend_from_slice(sender);
        out.extend_from_slice(&self.sequence.to_be_bytes());
        out.extend_from_slice(&self.issued_at.0.to_be_bytes());
        out.extend_from_slice(self.idempotency_key.as_bytes());
        out.extend_from_slice(&self.payload_len.to_be_bytes());
        Ok(out)
    }

    /// Encode a complete frame: header followed by `payload`.
    ///
    /// # Errors
    /// [`EncryptError::FramePayloadLengthMismatch`] if `payload.len()` differs
    /// from [`Self::payload_len`] (a header that lies about its payload is never
    /// written), plus [`Self::encode`]'s errors.
    pub fn encode_frame(&self, payload: &[u8]) -> Result<Vec<u8>, EncryptError> {
        if u32::try_from(payload.len()).ok() != Some(self.payload_len) {
            return Err(EncryptError::FramePayloadLengthMismatch);
        }
        let mut out = self.encode()?;
        out.extend_from_slice(payload);
        Ok(out)
    }

    /// Parse exactly one header; trailing bytes are an error.
    ///
    /// # Errors
    /// Every rejection listed in the module docs.
    pub fn decode(bytes: &[u8]) -> Result<Self, EncryptError> {
        let (header, rest) = Self::decode_prefix(bytes)?;
        if rest.is_empty() {
            Ok(header)
        } else {
            Err(EncryptError::FrameTrailingBytes)
        }
    }

    /// Parse a complete frame and return the header and the payload, which
    /// must be exactly `payload_len` bytes.
    ///
    /// # Errors
    /// Every header rejection, [`EncryptError::FrameTruncated`] for a short
    /// payload and [`EncryptError::FrameTrailingBytes`] for extra bytes.
    pub fn decode_frame(bytes: &[u8]) -> Result<(Self, &[u8]), EncryptError> {
        let (header, rest) = Self::decode_prefix(bytes)?;
        let want =
            usize::try_from(header.payload_len).map_err(|_| EncryptError::FramePayloadTooLarge)?;
        match rest.len().cmp(&want) {
            core::cmp::Ordering::Less => Err(EncryptError::FrameTruncated),
            core::cmp::Ordering::Greater => Err(EncryptError::FrameTrailingBytes),
            core::cmp::Ordering::Equal => Ok((header, rest)),
        }
    }

    fn decode_prefix(bytes: &[u8]) -> Result<(Self, &[u8]), EncryptError> {
        let short = EncryptError::FrameTruncated;
        let mut r = Cursor { rest: bytes };

        if r.take(FRAME_MAGIC.len()).ok_or(short)? != FRAME_MAGIC {
            return Err(EncryptError::FrameBadMagic);
        }
        let version = r.u16().ok_or(short)?;
        if version != FRAME_VERSION {
            return Err(EncryptError::FrameUnsupportedVersion(version));
        }
        let profile_id = r.u16().ok_or(short)?;
        let profile = HarwCryptoProfile::from_id(profile_id)
            .ok_or(EncryptError::FrameUnknownProfile(profile_id))?;
        let purpose_code = r.u8().ok_or(short)?;
        let purpose = HarwKeyPurpose::from_code(purpose_code)
            .ok_or(EncryptError::FrameUnknownPurpose(purpose_code))?;
        let key_version = HarwKeyVersion::new(r.u32().ok_or(short)?)?;
        let key_id_len = usize::from(r.u8().ok_or(short)?);
        let key_id = NodeId::from_wire(r.take(key_id_len).ok_or(short)?)?;
        let sender_len = usize::from(r.u8().ok_or(short)?);
        let sender = NodeId::from_wire(r.take(sender_len).ok_or(short)?)?;
        let sequence = r.u64().ok_or(short)?;
        let issued_at = UnixMillis(r.u64().ok_or(short)?);
        let idempotency_key = IdempotencyKey(r.array().ok_or(short)?);
        let payload_len = r.u32().ok_or(short)?;

        let header = Self {
            profile,
            purpose,
            key_id,
            key_version,
            sender,
            sequence,
            issued_at,
            idempotency_key,
            payload_len,
        };
        header.validate()?;
        Ok((header, r.rest))
    }
}
