//! Error type of `harw-completions`.
//!
//! Spec source: `harw-completions-CODING-DESIGN.md` §1 (src/error.rs).
//!
//! # Responsibility
//! Carries [`CompletionError`], the single error type of this crate, and the
//! crate-internal [`io_err`] helper that attaches operation and path context
//! to an [`std::io::Error`].
//!
//! # Concurrency
//! `CompletionError` is `Send + Sync` (only `String`, `&'static str` and
//! `std::io::Error` fields).
//!
//! # Errors
//! `Display`, `std::error::Error` and the `CompletionResult<T>` alias are
//! generated by `#[derive(harw_macros::HarwError)]`.
//!
//! # Examples
//! ```
//! use harw_completions::CompletionError;
//!
//! let err = CompletionError::UnsupportedShell { shell: "tcsh".to_owned() };
//! assert!(err.to_string().contains("tcsh"));
//! ```

use std::path::Path;

use harw_macros::HarwError;

/// Errors produced while generating, installing or removing completions.
#[derive(Debug, HarwError)]
pub enum CompletionError {
    /// `$HOME` is not set (or empty), so no per-user location can be resolved.
    #[msg("cannot determine the home directory: $HOME is not set")]
    HomeMissing,

    /// The requested shell has no supported install location.
    #[msg("unsupported shell '{shell}' (supported: bash, zsh, fish, elvish, powershell)")]
    UnsupportedShell {
        /// Name of the unsupported shell.
        shell: String,
    },

    /// `$SHELL` is unset, empty or names an unknown shell.
    #[msg(
        "cannot detect the shell from $SHELL ('{value}'); pass it explicitly, e.g. `completions zsh`"
    )]
    ShellUndetected {
        /// Raw `$SHELL` value (empty when unset).
        value: String,
    },

    /// The canonical target exists but is not a harw-managed completion file.
    #[msg("refusing to overwrite '{path}': it is not a harw-managed completion file")]
    ForeignTarget {
        /// The file that would have been overwritten.
        path: String,
    },

    /// A filesystem or stdout operation failed.
    #[msg("{op} '{path}' failed: {source}")]
    Io {
        /// Operation that failed (e.g. `"write"`, `"remove"`, `"read"`).
        op: &'static str,
        /// Affected path (`"<stdout>"` for stdout writes).
        path: String,
        /// Underlying I/O cause.
        source: std::io::Error,
    },
}

/// Returns a closure mapping an [`std::io::Error`] to [`CompletionError::Io`]
/// with the given operation and path (design doc §1, src/error.rs).
pub(crate) fn io_err(
    op: &'static str,
    path: &Path,
) -> impl FnOnce(std::io::Error) -> CompletionError {
    let path = path.display().to_string();
    move |source| CompletionError::Io { op, path, source }
}
