//! Backend B (`--native`): a generated crate plus `cargo build --release`.
//!
//! [`native_crate`] is pure and deterministic (golden-tested); everything
//! with side effects (finding sources and cargo, writing the crate into the
//! cache, running cargo) is in [`NativeBackend`].

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use serde::Serialize;

use crate::env::{CompilerEnv, HARW_VERSION};
use crate::error::CompileError;

/// Crate-relative path of the embedded artifact.
pub const NATIVE_ARTIFACT_FILE: &str = "agent.harwa";

/// What the generated crate links.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum NativeFlavor {
    /// A slim agent binary: `harw-agent-runner` with only the needed
    /// interface and tool-provider features.
    Runner,
    /// A complete, personalized harw: `harw-cli` with its default features
    /// and the user-interface agent baked in as the fixed root
    /// (`harw_cli::run_with_embedded_uia`). Chosen for a
    /// `role = "user-interface"` target.
    Harw,
}

/// Input of the code generator.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NativeSpec {
    /// What the crate links.
    pub flavor: NativeFlavor,
    /// Binary name (`[binary].name`).
    pub binary: String,
    /// Definition ID (for the header comment).
    pub definition_id: String,
    /// [`NativeFlavor::Harw`] only: the name of the personalized harw's own
    /// home (`~/.<name>`, `<project>/.<name>`).
    pub home_name: Option<String>,
    /// Definition version (the crate version).
    pub version: String,
    /// The harw source checkout (path dependencies).
    pub harw_src: PathBuf,
    /// Runner features: interfaces plus tool providers.
    pub features: BTreeSet<String>,
    /// The artifact bytes.
    pub artifact: Vec<u8>,
}

/// The generated files, crate-relative, in a fixed order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NativeCrate {
    /// Package name.
    pub package: String,
    /// `(path, bytes)`.
    pub files: Vec<(String, Vec<u8>)>,
}

impl NativeCrate {
    /// A generated file's text (`Cargo.toml`, `src/main.rs`).
    #[must_use]
    pub fn text(&self, path: &str) -> Option<String> {
        self.files
            .iter()
            .find(|(candidate, _)| candidate == path)
            .map(|(_, bytes)| String::from_utf8_lossy(bytes).into_owned())
    }
}

/// Package name of a generated runner crate: `harw-agent-<binary>` (a
/// personalized harw uses the binary name itself).
#[must_use]
pub fn package_name(binary: &str) -> String {
    format!("harw-agent-{binary}")
}

/// Generates the crate: `Cargo.toml`, `src/main.rs` and the artifact.
///
/// # Description
/// The output depends only on `spec`: features are sorted, paths are taken
/// as given, nothing records time or environment.
#[must_use]
pub fn native_crate(spec: &NativeSpec) -> NativeCrate {
    let package = match spec.flavor {
        NativeFlavor::Runner => package_name(&spec.binary),
        NativeFlavor::Harw => spec.binary.clone(),
    };
    let (cargo_toml, main_rs) = match spec.flavor {
        NativeFlavor::Runner => (runner_cargo_toml(spec, &package), runner_main_rs(spec)),
        NativeFlavor::Harw => (harw_cargo_toml(spec, &package), harw_main_rs(spec)),
    };
    NativeCrate {
        package,
        files: vec![
            ("Cargo.toml".to_owned(), cargo_toml.into_bytes()),
            ("src/main.rs".to_owned(), main_rs.into_bytes()),
            (NATIVE_ARTIFACT_FILE.to_owned(), spec.artifact.clone()),
        ],
    }
}

/// A path as a TOML basic string (quoted, escaped).
fn toml_path(path: &Path) -> String {
    toml::Value::String(path.display().to_string()).to_string()
}

fn runner_cargo_toml(spec: &NativeSpec, package: &str) -> String {
    let runner_path = toml_path(&spec.harw_src.join("harw-agent-runner"));
    let artifact_path = toml_path(&spec.harw_src.join("harw-agent-artifact"));
    let features: String = spec
        .features
        .iter()
        .map(|feature| format!("    \"{feature}\",\n"))
        .collect();
    format!(
        "# Generated by `harw agent build --native` (harw {HARW_VERSION}) for\n\
         # {id} {version}. Do not edit: every build rewrites this crate.\n\
         \n\
         [package]\n\
         name = \"{package}\"\n\
         version = \"{version}\"\n\
         edition = \"2024\"\n\
         publish = false\n\
         \n\
         [[bin]]\n\
         name = \"{binary}\"\n\
         path = \"src/main.rs\"\n\
         \n\
         [dependencies]\n\
         harw-agent-artifact = {{ path = {artifact_path} }}\n\
         harw-agent-runner = {{ path = {runner_path}, default-features = false, features = [\n\
         {features}\
         ] }}\n\
         \n\
         [profile.release]\n\
         lto = \"thin\"\n\
         codegen-units = 16\n\
         strip = true\n\
         \n\
         # A standalone crate, not a member of the harw workspace.\n\
         [workspace]\n",
        id = spec.definition_id,
        version = spec.version,
        binary = spec.binary,
    )
}

fn runner_main_rs(spec: &NativeSpec) -> String {
    let verification = native_verification();
    format!(
        "//! `{binary}`: the agent {id} {version}, compiled by\n\
         //! `harw agent build --native` (harw {HARW_VERSION}).\n\
         //!\n\
         //! The artifact next to this crate is embedded verbatim; the runner\n\
         //! verifies its hashes before the agent starts.\n\
         \n\
         #![forbid(unsafe_code)]\n\
         \n\
         fn main() -> std::process::ExitCode {{\n\
         {verification}\
         \x20   harw_agent_runner::run_embedded(include_bytes!(\"../{NATIVE_ARTIFACT_FILE}\"))\n\
         }}\n",
        id = spec.definition_id,
        version = spec.version,
        binary = spec.binary,
    )
}

fn harw_cargo_toml(spec: &NativeSpec, package: &str) -> String {
    let cli_path = toml_path(&spec.harw_src.join("harw-cli"));
    let artifact_path = toml_path(&spec.harw_src.join("harw-agent-artifact"));
    format!(
        "# Generated by `harw agent build --native` (harw {HARW_VERSION}) for the\n\
         # user-interface agent {id} {version}: a complete harw with this agent\n\
         # as its fixed root. Do not edit: every build rewrites this crate.\n\
         \n\
         [package]\n\
         name = \"{package}\"\n\
         version = \"{version}\"\n\
         edition = \"2024\"\n\
         publish = false\n\
         \n\
         [[bin]]\n\
         name = \"{binary}\"\n\
         path = \"src/main.rs\"\n\
         \n\
         [dependencies]\n\
         harw-agent-artifact = {{ path = {artifact_path} }}\n\
         # harw-cli with its default features: a normal harw.\n\
         harw-cli = {{ path = {cli_path} }}\n\
         \n\
         [profile.release]\n\
         lto = \"thin\"\n\
         codegen-units = 16\n\
         \n\
         # A standalone crate, not a member of the harw workspace.\n\
         [workspace]\n",
        id = spec.definition_id,
        version = spec.version,
        binary = spec.binary,
    )
}

fn harw_main_rs(spec: &NativeSpec) -> String {
    let verification = native_verification();
    format!(
        "//! `{binary}`: a personalized harw (harw {HARW_VERSION}) with the\n\
         //! user-interface agent {id} {version} as its fixed root, compiled by\n\
         //! `harw agent build --native`.\n\
         //!\n\
         //! It is a complete harw with its own, independent home `~/.{home}`\n\
         //! (project-local: `.{home}`); nothing is inherited from `~/.harw`.\n\
         //! The embedded agent is the fixed root.\n\
         \n\
         #![forbid(unsafe_code)]\n\
         \n\
         fn main() -> std::process::ExitCode {{\n\
         {verification}\
         \x20   harw_cli::run_with_embedded_uia(\n\
         \x20       include_bytes!(\"../{NATIVE_ARTIFACT_FILE}\"),\n\
         \x20       harw_cli::HomeChoice::Named(\"{home}\"),\n\
         \x20   )\n\
         }}\n",
        id = spec.definition_id,
        version = spec.version,
        binary = spec.binary,
        home = spec.home_name.as_deref().unwrap_or("harw-uia"),
    )
}

fn native_verification() -> String {
    format!(
        "    if let Err(error) = harw_agent_artifact::EmbeddedArtifact::verify_current_exe_matches(\n\
         \x20       include_bytes!(\"../{NATIVE_ARTIFACT_FILE}\"),\n\
         \x20   ) {{\n\
         \x20       eprintln!(\"agent integrity check failed: {{error}}\");\n\
         \x20       return std::process::ExitCode::FAILURE;\n\
         \x20   }}\n"
    )
}

/// Finds `cargo`: every `PATH` entry, then `~/.cargo/bin`.
///
/// # Errors
/// [`CompileError::ToolchainMissing`] naming the searched locations.
pub fn find_cargo(env: &CompilerEnv) -> Result<PathBuf, CompileError> {
    let name = if cfg!(windows) { "cargo.exe" } else { "cargo" };
    let mut searched: Vec<PathBuf> = Vec::new();
    if let Some(path) = &env.path_var {
        for dir in std::env::split_paths(path) {
            searched.push(dir.join(name));
        }
    }
    if let Some(home) = &env.user_home {
        searched.push(home.join(".cargo").join("bin").join(name));
    }
    searched
        .iter()
        .find(|candidate| candidate.is_file())
        .cloned()
        .ok_or(CompileError::ToolchainMissing { searched })
}

/// Where the harw sources come from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum SourcesOrigin {
    /// `--harw-src`.
    Flag,
    /// `HARW_SRC`.
    Env,
    /// The install record.
    InstallRecord,
}

/// Finds the harw sources: `--harw-src`, `HARW_SRC`, the install record.
///
/// # Errors
/// [`CompileError::SourcesMissing`] if none is set or the directory does
/// not contain the runner crate.
pub fn find_sources(
    env: &CompilerEnv,
    flag: Option<&Path>,
    flavor: NativeFlavor,
) -> Result<(PathBuf, SourcesOrigin), CompileError> {
    let candidate = flag
        .map(|path| (env.resolve(path), SourcesOrigin::Flag))
        .or_else(|| {
            env.env_harw_src
                .clone()
                .map(|path| (path, SourcesOrigin::Env))
        })
        .or_else(|| {
            env.install_record()
                .and_then(|record| record.source_dir)
                .map(|path| (path, SourcesOrigin::InstallRecord))
        });
    let Some((dir, origin)) = candidate else {
        return Err(CompileError::SourcesMissing {
            candidate: None,
            reason: "no source directory is known".to_owned(),
        });
    };
    if !dir.join("Cargo.toml").is_file() {
        return Err(CompileError::SourcesMissing {
            candidate: Some(dir),
            reason: "it has no Cargo.toml".to_owned(),
        });
    }
    let (needed, why) = match flavor {
        NativeFlavor::Runner => (
            "harw-agent-runner",
            "it has no harw-agent-runner crate (the runner arrives with #22 wave 3; update the checkout)",
        ),
        NativeFlavor::Harw => ("harw-cli", "it has no harw-cli crate"),
    };
    if !dir.join(needed).join("Cargo.toml").is_file() {
        return Err(CompileError::SourcesMissing {
            candidate: Some(dir),
            reason: why.to_owned(),
        });
    }
    Ok((dir, origin))
}

/// The cache key of a native build: artifact, features, target, harw
/// version and source directory.
#[must_use]
pub fn cache_key(
    artifact_digest: &str,
    features: &BTreeSet<String>,
    target: &str,
    src: &Path,
) -> String {
    let mut material = format!(
        "{artifact_digest}\n{target}\n{HARW_VERSION}\n{}\n",
        src.display()
    );
    for feature in features {
        material.push_str(feature);
        material.push('\n');
    }
    harw_agent_artifact::ArtifactDigest::of(material.as_bytes())
        .to_hex()
        .chars()
        .take(32)
        .collect()
}

/// Writes `bytes` to `path` unless the file already has exactly these bytes
/// (keeps mtimes stable, so cargo's fingerprints stay valid).
fn write_if_changed(path: &Path, bytes: &[u8]) -> Result<(), CompileError> {
    if std::fs::read(path).is_ok_and(|existing| existing == bytes) {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(CompileError::io(format!("create {}", parent.display())))?;
    }
    std::fs::write(path, bytes).map_err(CompileError::io(format!("write {}", path.display())))
}

/// A finished native build.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeOutput {
    /// What the crate links.
    pub flavor: NativeFlavor,
    /// The generated crate directory.
    pub crate_dir: PathBuf,
    /// The binary cargo produced (inside the shared target dir).
    pub binary: PathBuf,
    /// The harw sources used.
    pub harw_src: PathBuf,
    /// Where they came from.
    pub sources_origin: SourcesOrigin,
    /// The cargo executable used.
    pub cargo: PathBuf,
}

/// Runs the native backend.
#[derive(Debug, Clone)]
pub struct NativeBackend<'a> {
    /// The environment.
    pub env: &'a CompilerEnv,
    /// `--harw-src`.
    pub harw_src: Option<&'a Path>,
    /// Target triple (`--target`, else the host).
    pub target: &'a str,
}

impl NativeBackend<'_> {
    /// Checks the prerequisites (sources, cargo) without building.
    ///
    /// # Errors
    /// As [`find_sources`] and [`find_cargo`].
    pub fn prerequisites(
        &self,
        flavor: NativeFlavor,
    ) -> Result<(PathBuf, SourcesOrigin, PathBuf), CompileError> {
        let (src, origin) = find_sources(self.env, self.harw_src, flavor)?;
        let cargo = find_cargo(self.env)?;
        Ok((src, origin, cargo))
    }

    /// Generates the crate into the cache and runs `cargo build --release`.
    ///
    /// # Description
    /// The crate goes to `~/.harw/cache/agent-builds/<key>/` together with
    /// the source checkout's `rust-toolchain.toml` (so rustup picks the
    /// pinned toolchain) and `Cargo.lock` (same dependency versions as harw).
    /// All builds share `~/.harw/cache/agent-builds/target`, so harw's crates
    /// compile once. Cargo's output goes to stderr.
    ///
    /// # Errors
    /// Prerequisite errors, [`CompileError::Io`], or
    /// [`CompileError::CargoFailed`].
    #[allow(clippy::too_many_arguments)]
    pub fn build(
        &self,
        flavor: NativeFlavor,
        home_name: Option<&str>,
        binary: &str,
        definition_id: &str,
        version: &str,
        artifact: &harw_agent_artifact::Artifact,
        features: &BTreeSet<String>,
        progress: &mut dyn FnMut(&str),
    ) -> Result<NativeOutput, CompileError> {
        let (harw_src, sources_origin, cargo) = self.prerequisites(flavor)?;
        let digest = artifact.digest().to_hex();
        let key = cache_key(&digest, features, self.target, &harw_src);
        let cache = self.env.build_cache_dir();
        let crate_dir = cache.join(&key);
        let generated = native_crate(&NativeSpec {
            flavor,
            home_name: home_name.map(str::to_owned),
            binary: binary.to_owned(),
            definition_id: definition_id.to_owned(),
            version: version.to_owned(),
            harw_src: harw_src.clone(),
            features: features.clone(),
            artifact: artifact.to_bytes(),
        });
        progress(&format!(
            "generating {} in {}",
            generated.package,
            crate_dir.display()
        ));
        for (path, bytes) in &generated.files {
            write_if_changed(&crate_dir.join(path), bytes)?;
        }
        for shared in ["rust-toolchain.toml", "Cargo.lock"] {
            if let Ok(bytes) = std::fs::read(harw_src.join(shared)) {
                write_if_changed(&crate_dir.join(shared), &bytes)?;
            }
        }
        let blobs = crate::cache::store_blobs(&cache, artifact)?;
        crate::cache::CacheStamp {
            harw_version: HARW_VERSION.to_owned(),
            name: binary.to_owned(),
            artifact_digest: digest,
            target: self.target.to_owned(),
            last_used: crate::cache::unix_now(),
            blobs,
        }
        .write(&crate_dir)?;

        let target_dir = cache.join(crate::cache::TARGET_DIR);
        let mut command = Command::new(&cargo);
        command
            .arg("build")
            .arg("--release")
            .arg("--manifest-path")
            .arg(crate_dir.join("Cargo.toml"))
            .current_dir(&crate_dir)
            .env("CARGO_TARGET_DIR", &target_dir)
            .stdin(Stdio::null())
            .stdout(stderr_stdio())
            .stderr(Stdio::inherit());
        if self.target != self.env.host_target {
            command.arg("--target").arg(self.target);
        }
        progress(&format!(
            "running {} build --release (the first build compiles harw and can take minutes)",
            cargo.display()
        ));
        let status = command
            .status()
            .map_err(CompileError::io(format!("start {}", cargo.display())))?;
        if !status.success() {
            return Err(CompileError::CargoFailed {
                status: status.to_string(),
                crate_dir,
            });
        }
        let mut release = target_dir;
        if self.target != self.env.host_target {
            release.push(self.target);
        }
        release.push("release");
        let file_name = if self.target.contains("windows") {
            format!("{binary}.exe")
        } else {
            binary.to_owned()
        };
        Ok(NativeOutput {
            flavor,
            crate_dir,
            binary: release.join(file_name),
            harw_src,
            sources_origin,
            cargo,
        })
    }
}

/// Cargo's stdout goes to our stderr, so `--json` output stays clean.
fn stderr_stdio() -> Stdio {
    Stdio::from(std::io::stderr())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec() -> NativeSpec {
        NativeSpec {
            flavor: NativeFlavor::Runner,
            home_name: None,
            binary: "evidence-critic".to_owned(),
            definition_id: "harwness.agent.evidence-critic@1".to_owned(),
            version: "1.0.0".to_owned(),
            harw_src: PathBuf::from("/opt/harw-src"),
            features: ["cli", "core", "knowledge", "mcp", "tool-doc", "tool-fs"]
                .iter()
                .map(|feature| (*feature).to_owned())
                .collect(),
            artifact: b"HARWAGNT-test".to_vec(),
        }
    }

    fn golden(name: &str) -> String {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("golden")
            .join("native")
            .join(name);
        std::fs::read_to_string(path).unwrap_or_default()
    }

    /// Set `HARW_UPDATE_GOLDEN=1` to rewrite the golden files.
    fn check_golden(name: &str, actual: &str) {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("golden")
            .join("native")
            .join(name);
        if std::env::var_os("HARW_UPDATE_GOLDEN").is_some() {
            let written = std::fs::create_dir_all(path.parent().unwrap_or(Path::new(".")))
                .and_then(|()| std::fs::write(&path, actual));
            assert!(written.is_ok(), "write {}", path.display());
            return;
        }
        assert_eq!(actual, golden(name), "golden file {name} differs");
    }

    #[test]
    fn test_native_codegen_matches_the_golden_files() {
        let generated = native_crate(&spec());
        assert_eq!(generated.package, "harw-agent-evidence-critic");
        let paths: Vec<&str> = generated
            .files
            .iter()
            .map(|(path, _)| path.as_str())
            .collect();
        assert_eq!(paths, ["Cargo.toml", "src/main.rs", "agent.harwa"]);
        let cargo_toml = generated.text("Cargo.toml").unwrap_or_default();
        let main_rs = generated.text("src/main.rs").unwrap_or_default();
        check_golden(
            "Cargo.toml.golden",
            &cargo_toml.replace(HARW_VERSION, "<harw-version>"),
        );
        check_golden(
            "main.rs.golden",
            &main_rs.replace(HARW_VERSION, "<harw-version>"),
        );
        assert!(
            toml::from_str::<toml::Table>(&cargo_toml).is_ok(),
            "the generated Cargo.toml parses"
        );
    }

    #[test]
    fn test_native_codegen_for_the_uia_is_a_complete_harw() {
        let mut uia = spec();
        uia.flavor = NativeFlavor::Harw;
        uia.binary = "harw-mia".to_owned();
        uia.definition_id = "user.agent.mia@1".to_owned();
        uia.home_name = Some("mia".to_owned());
        let generated = native_crate(&uia);
        let cargo_toml = generated.text("Cargo.toml").unwrap_or_default();
        let main_rs = generated.text("src/main.rs").unwrap_or_default();
        check_golden(
            "Cargo.uia.toml.golden",
            &cargo_toml.replace(HARW_VERSION, "<harw-version>"),
        );
        check_golden(
            "main.uia.rs.golden",
            &main_rs.replace(HARW_VERSION, "<harw-version>"),
        );
        assert!(main_rs.contains("harw_cli::run_with_embedded_uia"));
        assert!(!cargo_toml.contains("harw-agent-runner"));
        assert!(toml::from_str::<toml::Table>(&cargo_toml).is_ok());
    }

    #[test]
    fn test_native_codegen_is_deterministic_and_feature_order_independent() {
        let first = native_crate(&spec());
        let mut reordered = spec();
        reordered.features = reordered.features.into_iter().rev().collect();
        assert_eq!(first, native_crate(&reordered));
    }

    #[test]
    fn test_missing_sources_and_toolchain_are_clear_errors() -> Result<(), String> {
        let env = CompilerEnv::isolated(PathBuf::from("/nonexistent/home"), PathBuf::from("/"));
        let error = find_sources(&env, None, NativeFlavor::Runner)
            .err()
            .ok_or("no sources are known, yet sources were found")?;
        assert!(error.to_string().contains("--harw-src"));
        let error = find_sources(
            &env,
            Some(Path::new("/nonexistent/src")),
            NativeFlavor::Harw,
        )
        .err()
        .ok_or("the flag names a missing directory")?;
        assert!(matches!(
            error,
            CompileError::SourcesMissing {
                candidate: Some(_),
                ..
            }
        ));
        let error = find_cargo(&env)
            .err()
            .ok_or("no PATH and no HOME, yet cargo was found")?;
        assert!(error.to_string().contains("rustup.rs"));
        Ok(())
    }

    #[test]
    fn test_cache_key_changes_with_every_input() {
        let features: BTreeSet<String> = ["core".to_owned()].into();
        let src = Path::new("/src");
        let base = cache_key("aa", &features, "x86_64-unknown-linux-gnu", src);
        assert_eq!(base.len(), 32);
        assert_ne!(
            base,
            cache_key("ab", &features, "x86_64-unknown-linux-gnu", src)
        );
        assert_ne!(
            base,
            cache_key("aa", &BTreeSet::new(), "x86_64-unknown-linux-gnu", src)
        );
        assert_ne!(
            base,
            cache_key("aa", &features, "aarch64-unknown-linux-gnu", src)
        );
        assert_ne!(
            base,
            cache_key(
                "aa",
                &features,
                "x86_64-unknown-linux-gnu",
                Path::new("/other")
            )
        );
    }
}
