[package]
name = "harw-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
harw-agent-dsl = { path = "../harw-agent-dsl" }
harw-fsutil = { path = "../harw-fsutil" }
harw-types = { path = "../harw-types" }
harw-macros = { path = "../harw-macros" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3.53", features = ["serde-well-known", "formatting", "parsing"] }
toml = "0.8"
toml_edit = "0.25.13"
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
