[package]
publish.workspace = true
name = "harw-install"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
getrandom = "0.4.3"
harw-config = { path = "../harw-config" }
harw-home = { path = "../harw-home" }
jiff = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
toml_edit = "0.25.13"

[lints]
workspace = true
