[package]
publish.workspace = true
name = "harw-observe"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
harw-authority = { path = "../harw-authority" }
harw-macros = { path = "../harw-macros" }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
